### ISSUE TITLE
Separate components for pages

### ISSUE THREAD

**Issue by eug-vs** [ilyayudovin/which#32]
We want to restructure `src/` to look contain two directories:
  - `components` - here we will place general reusable components (if any)
 -  `pages` - place for page-components, e.g `FeedPage`, `ProfilePage`, each of them will basically do all the stuff which was previously in `index.ts`. At this point `index.ts` should only call `<FeedPage />`, `<ProfilePage />` based on some simple conditions.

Motivation for that is to make `index.ts` as simple as possible.

**Comment by eug-vs** [comment]
All the components, which are only reusable within a certain page, should be located in that page's folder. 
Components which are globally reusable on multiple pages (like Header, Feed) go in `components`.

**Comment by ilyayudovin** [comment]
> We want to restructure `src/` to look contain two directories:
> 
>   - `components` - here we will place general reusable components (if any)
> 
>  -  `pages` - place for page-components, e.g `FeedPage`, `ProfilePage`, each of them will basically do all the stuff which was previously in `index.ts`. At this point `index.ts` should only call `<FeedPage />`, `<ProfilePage />` based on some simple conditions.
> 
> 
> 
> Motivation for that is to make `index.ts` as simple as possible.

Ok,got it.
